# ----------- CONFIGURABLE START -----------
title:            "Edme's Garden"
description:      "Tis her mind, tread carefully and carry a big gun."
domain:           edamame-v.github.io
url:              https://edamame-v.github.io # Site url, without a slash at the end.
signoff:          "Edme" # Your name

#--------- BWHAHAA -------------------

collections:
  categories:
    output: true


 
defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"